[package]
name = "robber"
version = "0.1.0"
authors = ["dbdr <dbdr@codingame.com>"]
edition = "2018"

[dependencies]
cargo_metadata = "0.9"
quote = "1.0"
syn = { version = "1.0", features = ["full", "visit-mut"] }
proc-macro2 = "1.0"
